#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug  6 10:14:26 2017

@author: k
"""

import sqlite3
conn = sqlite3.connect('test.db')
print('success')

conn.execute('''Table:
    (NAME           TEXT    NOT NULL,
     AGE            INT     NOT NULL,
     ADDRESS        CHAR(50),
     SALARY         REAL);''')
print('Table created successfully')

conn.close()
    